name: React Deployment

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
          node-version: '14'

    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Setup Pages
      if: github.ref == 'refs/heads/main'
      uses: actions/configure-pages@v3

    - name: Install dependencies and build React app
      run: |
        npm install axios
        npm install
    
    - name: Deploy GitHub Pages site
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: build
    